---
# parm_lpar_names:
# parm_lpar_ins_files:
# parm_lpar_prm_configs:

#parm_lpar_names: "{{ q('list', env.cluster.nodes.control.lpar_name) | flatten }}"
#parm_lpar_ins_files: "{{ q('list', env.cluster.nodes.control.lpar_ins_file) | flatten }}"
#parm_lpar_prm_files: "{{ q('list', env.cluster.nodes.control.lpar_prm_file) | flatten }}"
#parm_lpar_prm_configs: "{{ q('list', env.cluster.nodes.control.lpar_prm_config) | flatten }}"


_zhmc_auth:
  userid: "{{ _node.hmc.auth.user }}"
  password: "{{ _node.hmc.auth.pass }}"
  verify: false
