---

- name: Install CoreOS on compute nodes
  tags: create_compute_nodes
  ansible.builtin.shell: |
    virsh destroy {{ env.cluster.nodes.compute.vm_name[i] }} || true
    virsh undefine {{ env.cluster.nodes.compute.vm_name[i] }} --remove-all-storage --nvram || true
    # Define CPU model based on architecture
    CPU_MODEL="--cpu host"
    if [ $(uname -m) == "aarch64" ]; then
      # arm64 does not support host as CPU model
      CPU_MODEL="--cpu host-passthrough"
    fi
    virt-install \
    --name {{ env.cluster.nodes.compute.vm_name[i] }} \
    --osinfo detect=on,name={{ ('rhel9-unknown') if rhcos_os_variant is not defined else (rhcos_os_variant) }} \
    --autostart \
    --disk pool={{ env.cluster.networking.metadata_name }}-vdisk,size={{ env.cluster.nodes.compute.disk_size }},cache=none,io=native,serial={{ env.cluster.nodes.compute.vm_name[i] }}-boot \
    --iothreads 2 \
    --ram {{ env.cluster.nodes.compute.ram }} \
    ${CPU_MODEL} \
    --vcpus {{ env.cluster.nodes.compute.vcpu }} \
    --network network={{ env.vnet_name }}{{ (',mac=' + env.cluster.nodes.compute.mac[i]) if (env.cluster.nodes.compute.mac[i] is defined and env.use_dhcp) }} \
    --location {{ rhcos_download_url }},kernel={{ rhcos_live_kernel }},initrd={{ rhcos_live_initrd }} \
    --extra-args "rd.neednet=1 coreos.inst=yes coreos.inst.install_dev=vda" \
    --extra-args "coreos.live.rootfs_url=http://{{ env.bastion.networking.ip }}:8080/bin/{{ rhcos_live_rootfs }}" \
    {% if (env.cluster.nodes.compute.mac[i] is defined and env.use_dhcp) %}
    --extra-args "ip=dhcp" \
    {% else %}
    --extra-args "ip={{ env.cluster.nodes.compute.ip[i] }}::{{ env.cluster.networking.gateway }}:{{ env.cluster.networking.subnetmask }}:{{ env.cluster.nodes.compute.hostname[i] }}.{{ env.cluster.networking.metadata_name }}.{{ env.cluster.networking.base_domain }}:{{ env.cluster.networking.interface }}:none:1500" \
    --extra-args "{{ ('ip=[' + env.cluster.nodes.compute.ipv6[i] + ']::[' + env.cluster.networking.ipv6_gateway +']:' + env.cluster.networking.ipv6_prefix | string + '::' + env.cluster.networking.interface + ':none' ) if env.use_ipv6 == True else '' }}" \
    {% endif %}
    --extra-args "nameserver={{ env.cluster.networking.nameserver1 }}" \
    --extra-args "{{ ('nameserver=' + env.cluster.networking.nameserver2) if env.cluster.networking.nameserver2 is defined else '' }}" \
    --extra-args "coreos.inst.ignition_url=http://{{ env.bastion.networking.ip }}:8080/ignition/worker.ign" \
    --extra-args "{{ _vm_console }}" \
    --memballoon none \
    --graphics none \
    --wait=-1 \
    --noautoconsole
    {% if env.cluster.nodes.compute.disk2_size is defined %}
    sleep 10
    qemu-img create -o preallocation=full -f raw /var/lib/libvirt/images/{{ env.cluster.nodes.compute.vm_name[i] }}-2.img 5G
    qemu-img create -o preallocation=full -f raw /var/lib/libvirt/images/{{ env.cluster.nodes.compute.vm_name[i] }}-3.img 5G
    virsh attach-disk {{ env.cluster.nodes.compute.vm_name[i] }} /var/lib/libvirt/images/{{ env.cluster.nodes.compute.vm_name[i] }}-2.img --target vdb --config --live --cache none --io native
    virsh attach-disk {{ env.cluster.nodes.compute.vm_name[i] }} /var/lib/libvirt/images/{{ env.cluster.nodes.compute.vm_name[i] }}-3.img --target vdc --config --live --cache none --io native
    {% endif %}
#    {% if env.cluster.nodes.compute.disk2_size is defined %}
#    --disk pool={{ env.cluster.networking.metadata_name }}-vdisk,size={{ env.cluster.nodes.compute.disk2_size }},cache=none,io=native,serial={{ env.cluster.nodes.compute.vm_name[i] }}-data1 \
#    {% endif %}
  timeout: 450
  with_sequence: start=0 end={{ (env.cluster.nodes.compute.hostname | length) - 1 }} stride=1
  loop_control:
    extended: yes
    index_var: i
  when: env.cluster.nodes.compute.hostname[0] is defined and env.z.high_availability == False and inventory_hostname == env.z.lpar1.hostname

- name: Install CoreOS on infra nodes
  tags: create_compute_nodes
  ansible.builtin.shell: |
    # Define CPU model based on architecture
    CPU_MODEL="--cpu host"
    if [ $(uname -m) == "aarch64" ]; then
      # arm64 does not support host as CPU model
      CPU_MODEL="--cpu host-passthrough"
    fi
    virt-install \
    --name {{ env.cluster.nodes.infra.vm_name[i] }} \
    --osinfo detect=on,name={{ ('rhel9-unknown') if rhcos_os_variant is not defined else (rhcos_os_variant) }} \
    --autostart \
    --disk pool={{ env.cluster.networking.metadata_name }}-vdisk,size={{ env.cluster.nodes.infra.disk_size }},cache=none,io=native \
    {% if env.cluster.nodes.infra.disk2_size is defined %}
    --disk pool={{ env.cluster.networking.metadata_name }}-vdisk,size={{ env.cluster.nodes.infra.disk2_size }},cache=none,io=native \
    {% endif %}
    --ram {{ env.cluster.nodes.infra.ram }} \
    ${CPU_MODEL} \
    --vcpus {{ env.cluster.nodes.infra.vcpu }} \
    --network network={{ env.vnet_name }} \
    --location {{ rhcos_download_url }},kernel={{ rhcos_live_kernel }},initrd={{ rhcos_live_initrd }} \
    --extra-args "rd.neednet=1 coreos.inst=yes coreos.inst.install_dev=vda" \
    --extra-args "coreos.live.rootfs_url=http://{{ env.bastion.networking.ip }}:8080/bin/{{ rhcos_live_rootfs }}" \
    --extra-args "ip={{ env.cluster.nodes.infra.ip[i] }}::{{ env.cluster.networking.gateway }}:{{ env.cluster.networking.subnetmask }}:{{ env.cluster.nodes.infra.hostname[i] }}.{{ env.cluster.networking.metadata_name }}.{{ env.cluster.networking.base_domain }}:{{ env.cluster.networking.interface }}:none:1500" \
    --extra-args "{{ ('ip=[' + env.cluster.nodes.infra.ipv6[i] + ']::[' + env.cluster.networking.ipv6_gateway +']:' + env.cluster.networking.ipv6_prefix | string + '::' + env.cluster.networking.interface + ':none' ) if env.use_ipv6 == True else '' }}" \
    --extra-args "nameserver={{ env.cluster.networking.nameserver1 }}" \
    --extra-args "{{ ('nameserver=' + env.cluster.networking.nameserver2) if env.cluster.networking.nameserver2 is defined else '' }}" \
    --extra-args "coreos.inst.ignition_url=http://{{ env.bastion.networking.ip }}:8080/ignition/worker.ign" \
    --extra-args "{{ _vm_console }}" \
    --memballoon none \
    --graphics none \
    --wait=-1 \
    --noautoconsole
  with_sequence: start=0 end={{ ( env.cluster.nodes.infra.hostname | length ) - 1 }} stride=1
  loop_control:
    extended: yes
    index_var: i
  when: env.cluster.nodes.infra.hostname is defined and env.z.high_availability == False and inventory_hostname == env.z.lpar1.hostname

# If cluster is to be highly available, split control and infra nodes into lists corresponding to their future KVM hosts.

- name: Split information from compute nodes into groups. The number of groups being equal to the number of KVM hosts there are.
  tags: create_compute_nodes
  ansible.builtin.set_fact:
    compute_name: "{{ env.cluster.nodes.compute.vm_name[groups['kvm_host'].index(inventory_hostname)::groups['kvm_host'] | length] }}"
    compute_hostname: "{{ env.cluster.nodes.compute.hostname[groups['kvm_host'].index(inventory_hostname)::groups['kvm_host'] | length] }}"
    compute_ip: "{{ env.cluster.nodes.compute.ip[groups['kvm_host'].index(inventory_hostname)::groups['kvm_host'] | length] }}"
    compute_ipv6: "{{ env.cluster.nodes.compute.ipv6[groups['kvm_host'].index(inventory_hostname)::groups['kvm_host'] | length] }}"
  when: env.z.high_availability == True

- name: Split information for infra nodes into groups. The number of groups being equal to the number of KVM hosts there are.
  tags: create_compute_nodes
  ansible.builtin.set_fact:
    infra_name: "{{ env.cluster.nodes.infra.vm_name[groups['kvm_host'].index(inventory_hostname)::groups['kvm_host'] | length] }}"
    infra_hostname: "{{ env.cluster.nodes.infra.hostname[groups['kvm_host'].index(inventory_hostname)::groups['kvm_host'] | length] }}"
    infra_ip: "{{ env.cluster.nodes.infra.ip[groups['kvm_host'].index(inventory_hostname)::groups['kvm_host'] | length] }}"
    infra_ipv6: "{{ env.cluster.nodes.infra.ipv6[groups['kvm_host'].index(inventory_hostname)::groups['kvm_host'] | length] }}"
  when: env.z.high_availability == True and env.cluster.nodes.infra.hostname is defined

- name: Create CoreOS compute nodes on KVM hosts, if cluster is to be highly available.
  tags: create_compute_nodes
  ansible.builtin.shell: |
    # Define CPU model based on architecture
    CPU_MODEL="--cpu host"
    if [ $(uname -m) == "aarch64" ]; then
      # arm64 does not support host as CPU model
      CPU_MODEL="--cpu host-passthrough"
    fi
    virt-install \
    --name {{ compute_name[i] }} \
    --osinfo detect=on,name={{ ('rhel9-unknown') if rhcos_os_variant is not defined else (rhcos_os_variant) }} \
    --autostart \
    --disk pool={{ env.cluster.networking.metadata_name }}-vdisk,size={{ env.cluster.nodes.compute.disk_size }},cache=none,io=native \
    {% if env.cluster.nodes.compute.disk2_size is defined %}
    --disk pool={{ env.cluster.networking.metadata_name }}-vdisk,size={{ env.cluster.nodes.compute.disk2_size }},cache=none,io=native \
    {% endif %}
    --ram {{ env.cluster.nodes.compute.ram }} \
    ${CPU_MODEL} \
    --vcpus {{ env.cluster.nodes.compute.vcpu }} \
    --network network={{ env.vnet_name }}{{ (',mac=' + compute_mac[i] if (compute_mac[i] is defined and env.use_dhcp)) }} \
    --location {{ rhcos_download_url }},kernel={{ rhcos_live_kernel }},initrd={{ rhcos_live_initrd }} \
    --extra-args "rd.neednet=1 coreos.inst=yes coreos.inst.install_dev=vda" \
    --extra-args "coreos.live.rootfs_url=http://{{ env.bastion.networking.ip }}:8080/bin/{{ rhcos_live_rootfs }}" \
    {% if (compute_mac[i] is defined and env.use_dhcp) %}
    --extra-args "ip=dhcp" \
    {% else %}
    --extra-args "ip={{ compute_ip[i] }}::{{ env.cluster.networking.gateway }}:{{ env.cluster.networking.subnetmask }}:{{ compute_hostname[i] }}.{{ env.cluster.networking.metadata_name }}.{{ env.cluster.networking.base_domain }}:{{ env.cluster.networking.interface }}:none:1500" \
    --extra-args "{{ ('ip=[' + compute_ipv6[i] + ']::[' + env.cluster.networking.ipv6_gateway +']:' + env.cluster.networking.ipv6_prefix | string + '::' + env.cluster.networking.interface + ':none' ) if env.use_ipv6 == True else '' }}" \
    {% endif %}
    --extra-args "nameserver={{ env.cluster.networking.nameserver1 }}" \
    --extra-args "{{ ('nameserver=' + env.cluster.networking.nameserver2) if env.cluster.networking.nameserver2 is defined else '' }}" \
    --extra-args "coreos.inst.ignition_url=http://{{ env.bastion.networking.ip }}:8080/ignition/worker.ign" \
    --extra-args "{{ _vm_console }}" \
    --memballoon none \
    --graphics none \
    --wait=-1 \
    --noautoconsole
  loop: "{{ compute_name | zip(compute_hostname, compute_ip) | list }}"
  loop_control:
    extended: yes
    index_var: i
  when: env.z.high_availability == True and compute_hostname[i] is defined

- name: Create CoreOS infra nodes on KVM hosts, if cluster is to be highly available.
  tags: create_compute_nodes
  ansible.builtin.shell: |
    # Define CPU model based on architecture
    CPU_MODEL="--cpu host"
    if [ $(uname -m) == "aarch64" ]; then
      # arm64 does not support host as CPU model
      CPU_MODEL="--cpu host-passthrough"
    fi
    virt-install \
    --name {{ infra_name[i] }} \
    --osinfo detect=on,name={{ ('rhel9-unknown') if rhcos_os_variant is not defined else (rhcos_os_variant) }} \
    --autostart \
    --disk pool={{ env.cluster.networking.metadata_name }}-vdisk,size={{ env.cluster.nodes.infra.disk_size }},cache=none,io=native \
    {% if env.cluster.nodes.infra.disk2_size is defined %}
    --disk pool={{ env.cluster.networking.metadata_name }}-vdisk,size={{ env.cluster.nodes.infra.disk2_size }},cache=none,io=native \
    {% endif %}
    --ram {{ env.cluster.nodes.infra.ram }} \
    ${CPU_MODEL} \
    --vcpus {{ env.cluster.nodes.infra.vcpu }} \
    --network network={{ env.vnet_name }} \
    --location {{ rhcos_download_url }},kernel={{ rhcos_live_kernel }},initrd={{ rhcos_live_initrd }} \
    --extra-args "rd.neednet=1 coreos.inst=yes coreos.inst.install_dev=vda" \
    --extra-args "coreos.live.rootfs_url=http://{{ env.bastion.networking.ip }}:8080/bin/{{ rhcos_live_rootfs }}" \
    --extra-args "ip={{ infra_ip[i] }}::{{ env.cluster.networking.gateway }}:{{ env.cluster.networking.subnetmask }}:{{ infra_hostname[i] }}.{{ env.cluster.networking.metadata_name }}.{{ env.cluster.networking.base_domain }}:{{ env.cluster.networking.interface }}:none:1500" \
    --extra-args "{{ ('ip=[' + infra_ipv6[i] + ']::[' + env.cluster.networking.ipv6_gateway +']:' + env.cluster.networking.ipv6_prefix | string + '::' + env.cluster.networking.interface + ':none' ) if env.use_ipv6 == True else '' }}" \
    --extra-args "nameserver={{ env.cluster.networking.nameserver1 }}" \
    --extra-args "{{ ('nameserver=' + env.cluster.networking.nameserver2) if env.cluster.networking.nameserver2 is defined else '' }}" \
    --extra-args "coreos.inst.ignition_url=http://{{ env.bastion.networking.ip }}:8080/ignition/worker.ign" \
    --extra-args "{{ _vm_console }}" \
    --memballoon none \
    --graphics none \
    --wait=-1 \
    --noautoconsole
  loop: "{{ infra_name | zip(infra_hostname, infra_ip) | list }}"
  loop_control:
    extended: yes
    index_var: i
  when: env.cluster.nodes.infra.hostname is defined and infra_hostname[i] is defined and env.z.high_availability == True

- name: Attach compute node disks
  when: env.cluster.nodes.compute.vm_name[0] is defined and env.z.high_availability == False and inventory_hostname == env.z.lpar1.hostname
  tags: attach_compute_node_disks
  block:
    - name: Attach compute node disks
      ansible.builtin.shell: |
        VM_NAME="{{ env.cluster.nodes.compute.vm_name[i] }}"
        {% if env.cluster.nodes.compute.disk2_size is defined %}
        # Detach old disks, if exists
        virsh detach-disk "${VM_NAME}" --target vdb --live --persistent || true
        virsh detach-disk "${VM_NAME}" --target vdc --live --persistent || true
        # Create new disks
        virsh vol-create-as "{{ env.cluster.networking.metadata_name }}-vdisk" "${VM_NAME}-2.img" 5G --format raw
        virsh vol-create-as "{{ env.cluster.networking.metadata_name }}-vdisk" "${VM_NAME}-3.qcow2" 10G --format qcow2
        # Attach new disks
        virsh attach-disk "${VM_NAME}" "/var/lib/libvirt/images/${VM_NAME}-2.img" --target vdb --config --live \
        --cache none --io native --iothread 2 --serial=${VM_NAME}-data1
        virsh attach-disk "${VM_NAME}" "/var/lib/libvirt/images/${VM_NAME}-3.qcow2" --target vdc --config --live \
        --cache none --io native --iothread 2 --serial=${VM_NAME}-data2
        {% endif %}
        virsh domblklist "${VM_NAME}"
      timeout: 120
      with_sequence: start=0 end={{ (env.cluster.nodes.compute.hostname | length) - 1 }} stride=1
      loop_control:
        extended: yes
        index_var: i
      register: cmd_output

    - name: Debug, print above command output
      ansible.builtin.debug:
        var: cmd_output
# TODO
# {{ env.cluster.nodes.infra.disk2_size }}
