---
- name: Delete ignition folder for idempotency
  tags: get_ocp_disconnected
  file:
    path: /var/www/html/ignition
    state: absent

- name: Create directory bin for mirrors
  tags: get_ocp_disconnected
  become: true
  file:
    path: /var/www/html/bin
    state: directory
    mode: "0755"
    owner: "root"
    group: "root"

- name: Delete OCP download directory for idempotency, because ignition files deprecate after 24 hours.
  tags: get_ocp_disconnected
  become: true
  file:
    path: /root/ocpinst
    state: absent

- name: Create OCP download directory
  tags: get_ocp_disconnected
  file:
    path: /root/ocpinst
    state: directory

- name: Get Red Hat CoreOS rootfs file if it's not there already.
  tags: get_ocp_disconnected
  get_url:
    url: "{{ rhcos_download_url }}{{ rhcos_live_rootfs }}"
    dest: "/var/www/html/bin/{{ rhcos_live_rootfs }}"
    mode: "0644"

- name: Unzip OCP client and installer
  tags: get_ocp_disconnected
  ansible.builtin.unarchive:
    src: "{{ item }}"
    dest: /root/ocpinst/
    remote_src: yes
  loop:
    - "{{ ocp_download_url }}{{ ocp_client_tgz }}"
    - "{{ ocp_download_url }}{{ ocp_install_tgz }}"

- name: Copy kubectl, oc, and openshift-install binaries to /usr/local/sbin
  tags: get_ocp_disconnected
  become: true
  ansible.builtin.copy:
    src: /root/ocpinst/{{ item }}
    dest: /usr/sbin/{{ item }}
    owner: root
    group: root
    mode: "755"
    remote_src: yes
  loop:
    - kubectl
    - oc
    - openshift-install

- name: Capture hostname
  shell: hostname -f
  register: hostname_result

- name: Set local_registry variable
  set_fact:
    local_registry: "{{ hostname_result.stdout }}:8443"

- name: Login with authfile, and it will automatically include the login credential for this registry
  tags: install_mirror_registry
  become: true
  shell: podman login -u multiarch -p pass4multi --authfile /root/mirror_registry/pull-secret.json "{{ local_registry }}"

- name: Check pull-secret files
  tags: install_mirror_registry
  become: true
  shell: jq -c . /root/mirror_registry/pull-secret.json
  register: pullsecret

- name: Print pullsecret
  tags: install_mirror_registry
  debug:
    var: pullsecret.stdout_lines

- name: Capture replace_cert
  shell: |
    set -o pipefail
    cat /etc/pki/ca-trust/source/anchors/domain.crt | nl -bn -w 1
  register: replace_cert

- name: Use template file to create install-config and backup.
  tags: get_ocp_disconnected, patch_install_config
  vars:
    local_registry: local_registry
    pullsecret: pullsecret
    replace_cert: replace_cert
  template:
    src: install-config.yaml.j2
    dest: "{{ item }}"
    force: yes
  loop:
    - /root/ocpinst/install-config.yaml
    - /root/ocpinst/install-config-backup.yaml

- name: Capture OCP public key
  tags: get_ocp_disconnected
  shell: cat /root/.ssh/id_rsa.pub
  register: ocp_pub_key

- name: Place SSH key in install-config
  tags: get_ocp_disconnected, patch_install_config
  lineinfile:
    line: "sshKey: '{{ ocp_pub_key.stdout }}'"
    path: "{{ item }}"
  loop:
    - /root/ocpinst/install-config.yaml
    - /root/ocpinst/install-config-backup.yaml

- name: Create the installation program that is based on the mirrored content.
  tags: get_ocp_disconnected
  become: true
  shell: oc adm release extract -a /root/mirror_registry/pull-secret.json --command=openshift-install "{{ local_registry }}/"{{ mr_local_repository }}":"{{ mr_ocp_release }}"-"{{ mr_architecture }}""

- name: Create manifests
  tags: get_ocp_disconnected
  shell: /root/ocpinst/openshift-install create manifests --dir=/root/ocpinst/
  become: true

- name: Set masters schedulable parameter to false
  tags: get_ocp_disconnected
  become: true
  replace:
    path: /root/ocpinst/manifests/cluster-scheduler-02-config.yml
    regexp: ": true"
    replace: ": false"

- name: Set permissions for ocpinst directory contents to root
  tags: get_ocp_disconnected
  become: true
  shell: chmod 0755 /root/ocpinst/{{item}}
  loop:
    - manifests
    - openshift
    - .openshift_install.log
    - .openshift_install_state.json

- name: Set ownership of ocpinst directory contents to root
  tags: get_ocp_disconnected
  become: true
  shell: chown root:root /root/ocpinst/{{item}}
  loop:
    - manifests
    - openshift
    - .openshift_install.log
    - .openshift_install_state.json

- name: Create ignition files
  tags: get_ocp_disconnected
  become: true
  shell: /root/ocpinst/openshift-install create ignition-configs  --dir=/root/ocpinst/

- name: Set ownership to root and permissions of ignitions and related files.
  tags: get_ocp_disconnected
  file:
    state: "{{ item.state }}"
    path: /root/ocpinst/{{ item.path }}
    owner: root
    group: root
    mode: "{{ item.mode }}"
  loop:
    - { state: file, path: bootstrap.ign, mode: "755" }
    - { state: file, path: master.ign, mode: "755" }
    - { state: file, path: worker.ign, mode: "755" }
    - { state: directory, path: auth, mode: "755" }
    - { state: file, path: metadata.json, mode: "755" }
    - { state: file, path: auth/kubeconfig, mode: "644" }
    - { state: file, path: auth/kubeadmin-password, mode: "644" }

- name: Create directory in admin user's home for default kubeconfig.
  tags: get_ocp_disconnected, config
  become: false
  file:
    state: directory
    path: ~/.kube

- name: Create directory in root's home for default kubeconfig.
  tags: get_ocp_disconnected, config
  become: true
  file:
    state: directory
    path: ~/.kube

- name: Make kubeconfig admin user's default (for non-root user).
  tags: get_ocp_disconnected, config
  copy:
    src: /root/ocpinst/auth/kubeconfig
    dest: /home/{{ env.bastion.access.user }}/.kube/config
    owner: "{{ env.bastion.access.user }}"
    group: "{{ env.bastion.access.user }}"
    remote_src: yes
  when: env.bastion.access.user != "root"

- name: Make kubeconfig admin user's default (for root user).
  tags: get_ocp_disconnected, config
  copy:
    src: /root/ocpinst/auth/kubeconfig
    dest: /{{ env.bastion.access.user }}/.kube/config
    owner: "{{ env.bastion.access.user }}"
    group: "{{ env.bastion.access.user }}"
    remote_src: yes
  when: env.bastion.access.user == "root"

- name: Make kubeconfig root user's default.
  tags: get_ocp_disconnected, config
  copy:
    src: /root/ocpinst/auth/kubeconfig
    dest: /root/.kube/config
    owner: root
    group: root
    remote_src: yes

- name: Create ignition directory in HTTP-accessible directory.
  tags: get_ocp_disconnected
  become: true
  file:
    path: /var/www/html/ignition
    state: directory

- name: Copy ignition files to HTTP-accessible directory.
  tags: get_ocp_disconnected
  become: true
  copy:
    src: /root/ocpinst/{{ item }}.ign
    dest: /var/www/html/ignition
    remote_src: yes
    mode: "775"
    group: root
    owner: root
  loop:
    - bootstrap
    - master
    - worker
