---
- name: Debug issue with cancel
  ansible.builtin.debug:
    var: approve_certs_task

- name: Cancel async 'approve_certs_task', if exists
  tags: approve_certs
  when: approve_certs_task.ansible_job_id is defined and approve_certs_cleanup
  ansible.builtin.async_status:
    jid: "{{ approve_certs_task.ansible_job_id }}"
    mode: cleanup
  failed_when: false

- name: Approve all pending CSRs in the next 50 min (async task)
  tags: approve_certs
  when: not approve_certs_cleanup
  ansible.builtin.shell: |
    set -o pipefail
    for i in {1..90} ; do
        # Approve all pending requests
        oc get csr -o go-template='{{range .items}}{{if not .status}}{{.metadata.name}}{{"\n"}}{{end}}{{end}}' \
        | xargs --no-run-if-empty oc adm certificate approve
        sleep 30
    done
  # Run for 50 min
  async: 3000
  poll: 0
  register: approve_certs_task
