---
- name: Debug issue with cancel
  ansible.builtin.debug:
    var: approve_certs_task

- name: Cancel async 'approve_certs_task', if exists
  tags: approve_certs
  when: approve_certs_task is defined and approve_certs_cleanup
  ansible.builtin.async_status:
    jid: "{{ approve_certs_task.ansible_job_id }}"
    mode: cleanup
  failed_when: false
  ignore_errors: true

# TODO: Use this documented command to approve all pending csr's
# https://docs.openshift.com/container-platform/4.15/nodes/nodes/nodes-sno-worker-nodes.html#installation-approve-csrs_add-workers
# oc get csr -o go-template='{{range .items}}{{if not .status}}{{.metadata.name}}{{"\n"}}{{end}}{{end}}' | xargs --no-run-if-empty oc adm certificate approve

- name: Approve all pending CSRs in the next 45 min (async task)
  tags: approve_certs
  when: not approve_certs_cleanup
  ansible.builtin.shell: |
    set -o pipefail
    for i in {1..90} ; do
        # Approve all pending requests
        LIST=$(oc get csr 2> /dev/null | grep -i pending | awk '{print $1}')
        [ ! -z "${LIST}" ] && echo "${LIST}" | xargs oc adm certificate approve || true
        sleep 30
    done
  # Run for 45 min
  async: 2700
  poll: 0
  register: approve_certs_task
