---
- name: Debug issue with approve_certs_cleanup
  ansible.builtin.debug:
    var: approve_certs_cleanup

- name: Cancel async 'approve_certs_task', if exists
  tags: approve_certs
  when: approve_certs_task.ansible_job_id is defined and approve_certs_cleanup
  ansible.builtin.async_status:
    jid: "{{ approve_certs_task.ansible_job_id }}"
    mode: cleanup
  failed_when: false

- name: Approve all pending CSRs in the next 50 min (async task)
  tags: approve_certs
  when: not approve_certs_cleanup
  ansible.builtin.shell: |
    # Do not use pipefail
    for i in {1..100} ; do
        # Approve all pending requests
        LIST=$(oc get csr 2> /dev/null | grep -i pending | awk '{print $1}')
        if [ -n "$LIST" ]; then
            echo "$LIST" | xargs --no-run-if-empty oc adm certificate approve || true
        fi
        sleep 30
    done
  # Run for 50 min
  async: 3000
  poll: 0
  register: approve_certs_task

- name: Debug Async Job
  ansible.builtin.debug:
    msg: "Async job: {{ approve_certs_task }}"
  when: approve_certs_task is defined
