---

- name: Delete haproxy for port 80 and 443
  become: true
  block:
    - name: Delete haproxy port 80
      ansible.builtin.lineinfile:
        path: /etc/haproxy/haproxy.cfg
        state: absent
        regex: "{{ param_haproxy_ip }}:80 check"

    - name: Delete haproxy port 443
      ansible.builtin.lineinfile:
        path: /etc/haproxy/haproxy.cfg
        state: absent
        regex: "{{ param_haproxy_ip }}:443 check"
