---

- name: Check to see if local SSH directory exists
  tags: ssh_ocp_key_gen
  ansible.builtin.stat:
    path: /root/.ssh
  register: ssh_directory_exists_check

- name: Create SSH local directory if it doesn't already exist
  tags: ssh_ocp_key_gen
  ansible.builtin.file:
    path: /root/.ssh
    state: directory
    mode: "0700"
  register: ssh_directory_creation
  when: not ssh_directory_exists_check.stat.exists

- name: Generate an OpenSSH keypair (4096 bits, RSA)
  tags: ssh_ocp_key_gen
  community.crypto.openssh_keypair:
    path: "/root/.ssh/id_rsa"
    type: rsa
    size: 4096
    backend: opensshbin
    owner: root
    mode: "0600"
    passphrase: ""
    comment: "{{ env.ocp_ssh_key_comment }}"
    regenerate: full_idempotence
  register: ssh_ocp

- name: Print results of SSH key generation
  tags: ssh_ocp_key_gen
  ansible.builtin.debug:
    msg: "Public Key Generated: {{ ssh_ocp.public_key }}"

- name: Set SSH key permissions
  tags: ssh_ocp_key_gen
  ansible.builtin.command: chmod 600  /root/.ssh/{{ item }}
  loop:
    - id_rsa
    - id_rsa.pub

- name: Set SSH key ownership
  tags: ssh_ocp_key_gen
  ansible.builtin.command: chown root:root /root/.ssh/{{ item }}
  loop:
    - id_rsa
    - id_rsa.pub
