---

- name: Create SSH local directory if it doesn't already exist
  tags: ssh_ocp_key_gen
  ansible.builtin.file:
    path: /root/.ssh
    state: directory
    mode: "0700"
  register: ssh_directory_creation

- name: Generate an OpenSSH keypair (4096 bits, RSA)
  tags: ssh_ocp_key_gen
  community.crypto.openssh_keypair:
    path: "/root/.ssh/id_rsa"
    type: rsa
    size: 4096
    backend: opensshbin
    owner: root
    mode: "0600"
    passphrase: ""
    # TODO
    # comment: "{{ env.ocp_ssh_key_comment }}"
    regenerate: full_idempotence
  register: ssh_ocp

- name: Print results of SSH key generation
  tags: ssh_ocp_key_gen
  ansible.builtin.debug:
    msg: "Public Key Generated: {{ ssh_ocp.public_key }}"
