---

- name: Ensure the dpm mode partition is stopped
  ignore_errors: true
  ibm.ibm_zhmc.zhmc_partition:
    hmc_host: "{{ _node.hmc.host }}"
    hmc_auth: "{{ _zhmc_auth }}"
    cpc_name: "{{ _node.cpc_name }}"
    name: "{{ _node.lpar.name }}"
    state: stopped
    properties:
      description: "{{ _node.lpar.description }}"
      ifl_processors: "{{ _node.lpar.ifl.count }}"
      initial_memory: "{{ _node.lpar.ifl.initial_memory }}"
      maximum_memory: "{{ _node.lpar.ifl.max_memory }}"

- name: Configure an FTP boot server and start the dpm mode partition - debug
  ansible.builtin.shell: |
    '
    hmc_host: "{{ _node.hmc.host }}"
    hmc_auth: "{{ _zhmc_auth }}"
    cpc_name: "{{ _node.cpc_name }}"
    name: "{{ _node.lpar.name }}"
    state: active
    select_properties:
    properties:
      boot_device: ftp
      boot_ftp_host: "{{ env.z.hmc_ftp_server.ip }}"
      boot_ftp_username: "{{ env.z.hmc_ftp_server.user }}"
      boot_ftp_password: "{{ env.z.hmc_ftp_server.pass }}"
      boot_ftp_insfile: "{{ _hmc_load_from_ftp_file_path }}"
    '
  register: part1
- ansible.builtin.debug:
    var: part1

- name: Configure an FTP boot server and start the dpm mode partition
  ibm.ibm_zhmc.zhmc_partition:
    hmc_host: "{{ _node.hmc.host }}"
    hmc_auth: "{{ _zhmc_auth }}"
    cpc_name: "{{ _node.cpc_name }}"
    name: "{{ _node.lpar.name }}"
    state: active
    select_properties:
    properties:
      boot_device: ftp
      boot_ftp_host: "{{ env.z.hmc_ftp_server.ip }}"
      boot_ftp_username: "{{ env.z.hmc_ftp_server.user }}"
      boot_ftp_password: "{{ env.z.hmc_ftp_server.pass }}"
      boot_ftp_insfile: "{{ _hmc_load_from_ftp_file_path }}"
  register: part1
# TODO:
# Ignore ignore error:
# {"changed": false, "msg": "NotFound: Could not find VirtualSwitch using filter arguments ...
  failed_when: '"NotFound: Could not find VirtualSwitch" not in part1.msg'

- ansible.builtin.debug:
    var: part1
