---

- name: "Stop and configure the dpm mode partition {{ _host.lpar.name }}"
  ibm.ibm_zhmc.zhmc_partition:
    hmc_host: "{{ _host.hmc.host }}"
    hmc_auth:
      userid: "{{ _host.hmc.auth.user }}"
      password: "{{ _host.hmc.auth.pass }}"
      verify: false
    cpc_name: "{{ _host.cpc_name }}"
    name: "{{ _host.lpar.name }}"
    state: stopped
    properties:
      description: "{{ _host.lpar.description }}"
      ifl_processors: "{{ _host.lpar.ifl.count }}"
      initial_memory: "{{ _host.lpar.ifl.initial_memory }}"
      maximum_memory: "{{ _host.lpar.ifl.max_memory }}"
  register: part1

- name: Show above command output
  ansible.builtin.debug:
    var: part1

- name: Configure an FTP boot server and start the dpm mode partition - debug
  when: false
  block:
    - name: Configure an FTP boot server and start the dpm mode partition - debug
      ansible.builtin.shell: |
        echo '
        hmc_host: "{{ _host.hmc.host }}"
        hmc_auth:
          userid: "{{ _host.hmc.auth.user }}"
          password: "***"
          verify: false
        cpc_name: "{{ _host.cpc_name }}"
        name: "{{ _host.lpar.name }}"
        state: active
        select_properties:
        properties:
          boot_device: ftp
          boot_ftp_host: "{{ env.z.hmc_ftp_server.ip }}"
          boot_ftp_username: "{{ env.z.hmc_ftp_server.user }}"
          boot_ftp_password: "{{ env.z.hmc_ftp_server.pass }}"
          boot_ftp_insfile: "{{ _hmc_load_from_ftp_ins_file }}"
        '
      register: part1

    - name: Show above command output
      ansible.builtin.debug:
        var: part1

- name: "Configure an FTP boot server and start the dpm mode partition {{ _host.lpar.name }}"
  block:
    - name: "Configure an FTP boot server and start the dpm mode partition {{ _host.lpar.name }}"
      vars:
      ibm.ibm_zhmc.zhmc_partition:
        hmc_host: "{{ _host.hmc.host }}"
        hmc_auth:
          userid: "{{ _host.hmc.auth.user }}"
          password: "{{ _host.hmc.auth.pass }}"
          verify: false
        cpc_name: "{{ _host.cpc_name }}"
        name: "{{ _host.lpar.name }}"
        state: active
        select_properties:
        properties:
          boot_device: ftp
          boot_ftp_host: "{{ env.z.hmc_ftp_server.ip }}"
          boot_ftp_username: "{{ env.z.hmc_ftp_server.user }}"
          boot_ftp_password: "{{ env.z.hmc_ftp_server.pass }}"
          boot_ftp_insfile: "{{ _hmc_load_from_ftp_ins_file }}"
      register: part1

    - name: Show above command output
      ansible.builtin.debug:
        var: part1
