---

- name: Check role/task parameters
  ansible.builtin.fail:
    msg: "Error: loop control variable 'idx' is not defined"
  when: idx is not defined

- name: Include LPAR host variablese
  ansible.builtin.include_vars:
    file: "{{ inventory_dir }}/host_vars/{{ parm_lpar_names[idx] }}.yaml"
    name: _host

- name: Update local variable
  ansible.builtin.set_fact:
    _hmc_load_from_ftp_ins_file: "ftp/{{ _host.lpar.name }}.ins"

# TODO: For legacy reasons, can be deleted in future
- name: Create and upload prm file
  when: parm_lpar_prm_filenames[idx] is defined
  ansible.builtin.copy:
    dest: "{{ parm_lpar_prm_filenames[idx] }}"
    content: "{{ (_host.lpar_prm_config | join(' ') + ' ' + parm_lpar_prm_configs[idx]) + '\n' }}"
    mode: '0644'
  remote_user: "{{ env.z.hmc_ftp_server.user }}"
  delegate_to: "{{ env.z.hmc_ftp_server.ip }}"

- name: Create and upload prm file to new directory
  ansible.builtin.copy:
    dest: "~/ftp/images/{{ _host.lpar.name }}.prm"
    content: "{{ (_host.lpar_prm_config | join(' ') + ' ' + parm_lpar_prm_configs[idx]) + '\n' }}"
    mode: '0644'
  remote_user: "{{ env.z.hmc_ftp_server.user }}"
  delegate_to: "{{ env.z.hmc_ftp_server.ip }}"

- name: Create and upload ins file from template
  ansible.builtin.template:
    src: "lpar_ins.j2"
    dest: "~/ftp/{{ _host.lpar.name }}.ins"
    mode: "0644"
  remote_user: "{{ env.z.hmc_ftp_server.user }}"
  delegate_to: "{{ env.z.hmc_ftp_server.ip }}"

# TODO: For legacy reasons, can be deleted in future
- name: Define local variables
  when: parm_lpar_ins_filenames[idx] is defined
  ansible.builtin.set_fact:
    _hmc_load_from_ftp_ins_file: "{{ parm_lpar_ins_filenames[idx] }}"
    _hmc_load_from_ftp_ins_filename: "{{ parm_lpar_ins_filenames[idx] }}"

- name: Lood classic mode task
  when: (_host.cpc_dpm_enabled is defined and not _host.cpc_dpm_enabled) or _host.cpc_dpm_enabled is not defined
  ansible.builtin.include_tasks: "classic_mode.yaml"

- name: Lood dpm mode task
  when: _host.cpc_dpm_enabled is defined and _host.cpc_dpm_enabled
  ansible.builtin.include_tasks: "dpm_mode.yaml"
