---

- name: Check role/task parameters
  ansible.builtin.fail:
    msg: "Error: loop control variable 'idx' is not defined"
  when: idx is not defined

- name: Include LPAR host variablese
  ansible.builtin.include_vars:
    file: "{{ inventory_dir }}/host_vars/{{ parm_lpar_names[idx] }}.yaml"
    name: _node

- name: Lood classic mode task
  when: 1
  ansible.builtin.include_tasks: "classic_mode.yaml"

- name: Lood dpm mode task
  when: 0
#  _node.cpc_dpm_mode is defined and _node.cpc_dpm_mode
  ansible.builtin.include_tasks: "dpm_mode.yaml"
