---

- name: Check role/task parameters
  ansible.builtin.fail:
    msg: "Error: loop control variable 'idx' is not defined"
  when: idx is not defined

- name: Include LPAR host variablese
  ansible.builtin.include_vars:
    file: "{{ inventory_dir }}/host_vars/{{ parm_lpar_names[idx] }}.yaml"
    name: _host

- name: Update local variable
  ansible.builtin.set_fact:
    _hmc_load_from_ftp_ins_file: "{{ env.hmc_ftp_server.dir }}{{ _host.lpar.name }}.ins"

- name: Create required directories on HMC ftp server, if not already exists
  when: idx == 0
  ansible.builtin.shell: |
    mkdir -p "{{ env.file_server.ftp_dir }}iso"
    mkdir -p "{{ env.file_server.ftp_dir }}images"
  remote_user: "{{ env.file_server.user }}"
  delegate_to: "{{ env.file_server.ip }}"

- name: If not available, download Red Hat CoreOS ISO to HMC ftp server
  when: idx == 0
  ansible.builtin.get_url:
    url: "{{ item.baseurl }}{{ item.file }}"
    dest: "{{ env.file_server.ftp_dir }}iso/{{ item.file }}"
    mode: "0644"
  loop:
    - { baseurl: "{{ rhcos_download_url }}", file: "{{ rhcos_live_iso }}" }
  remote_user: "{{ env.file_server.user }}"
  delegate_to: "{{ env.file_server.ip }}"

# TODO: For legacy reasons, can be deleted in future
# - name: Create and upload lagacy prm file
#   when: parm_lpar_prm_filenames[idx] is defined
#   ansible.builtin.copy:
#     dest: "{{ parm_lpar_prm_filenames[idx] }}"
#     content: "{{ (_host.lpar_prm_config1 | join(' ') + ' ' + parm_lpar_prm_configs2[idx]) + '\n' }}"
#     mode: '0644'
#   remote_user: "{{ env.z.hmc_ftp_server.user }}"
#   delegate_to: "{{ env.z.hmc_ftp_server.ip }}"

- name: Extract boot artifacts from ISO, e.g. {{ rhcos_live_kernel }}"
  when: idx == 0
  ansible.builtin.shell: |
    set -e
    cd "{{ env.file_server.ftp_dir }}images"
    7z e "../iso/{{ rhcos_live_iso }}" -so images/pxeboot/kernel.img > "{{ rhcos_live_kernel }}"
    7z e "../iso/{{ rhcos_live_iso }}" -so images/pxeboot/initrd.img > "{{ rhcos_live_initrd }}"
    7z e "../iso/{{ rhcos_live_iso }}" -so images/initrd.addrsize > "{{ rhcos_live_initrd }}.addrsize"
  remote_user: "{{ env.file_server.user }}"
  delegate_to: "{{ env.file_server.ip }}"

#    Date      Time    Attr         Size   Compressed  Name
# ------------------- ----- ------------ ------------  ------------------------
# 2024-05-29 19:44:58 .....         2048         2048  boot.catalog
# 2024-05-29 19:44:58 D....                            coreos
# 2024-05-29 19:38:11 .....          684          684  coreos/features.json
# 2024-05-29 19:44:58 .....           76           76  coreos/igninfo.json
# 2024-05-29 19:44:58 .....          259          259  coreos/kargs.json
# 2024-05-29 19:44:58 .....        16384        16384  coreos/miniso.dat
# 2024-05-29 19:44:58 .....          149          149  generic.ins
# 2024-05-29 19:44:58 D....                            images
# 2024-05-29 19:44:58 .....     67210176     67210176  images/cdboot.img
# 2024-05-29 19:44:58 .....           91           91  images/cdboot.prm
# 2024-05-29 19:44:58 .....           91           91  images/generic.prm
# 2024-05-29 19:44:58 .....           91           91  images/genericdvd.prm
# 2024-05-29 19:44:58 .....           16           16  images/initrd.addrsize
# 2024-05-29 19:44:58 D....                            images/pxeboot
# 2024-05-29 19:44:58 .....     57686976     57686976  images/pxeboot/initrd.img
# 2024-05-29 19:38:11 .....      9257445      9257445  images/pxeboot/kernel.img
# 2024-05-29 19:44:54 .....    974301696    974301696  images/pxeboot/rootfs.img
# 2024-05-29 19:44:58 .....          163          163  images/redhat.exec
#                     .....     33553920     33553920  [BOOT]/Boot-NoEmul.img
# ------------------- ----- ------------ ------------  ------------------------
# 2024-05-29 19:44:58         1142030265   1142030265  16 files, 3 folders

- name: Create and upload prm file
  ansible.builtin.copy:
    dest: "{{ env.file_server.ftp_dir }}images/{{ _host.lpar.name }}.prm"
    content: "{{ (_host.lpar_prm_config1 | join(' ') + ' ' + parm_lpar_prm_configs2[idx]) + '\n' }}"
    mode: '0644'
  remote_user: "{{ env.file_server.user }}"
  delegate_to: "{{ env.file_server.ip }}"

- debug:
    var: _host.lpar_prm_config1

- name: Create and upload ins file from template
  ansible.builtin.template:
    src: "lpar_ins.j2"
    dest: "{{ env.file_server.ftp_dir }}{{ _host.lpar.name }}.ins"
    mode: "0644"
  remote_user: "{{ env.file_server.user }}"
  delegate_to: "{{ env.file_server.ip }}"

# TODO: For legacy reasons, can be deleted in future
# - name: Define local variables
#   when: parm_lpar_ins_filenames[idx] is defined
#   ansible.builtin.set_fact:
#     _hmc_load_from_ftp_ins_file: "{{ parm_lpar_ins_filenames[idx] }}"
#     _hmc_load_from_ftp_ins_filename: "{{ parm_lpar_ins_filenames[idx] }}"

- name: Lood classic mode task
  when: (_host.cpc_dpm_enabled is defined and not _host.cpc_dpm_enabled) or _host.cpc_dpm_enabled is not defined
  ansible.builtin.include_tasks: "classic_mode.yaml"

- name: Lood dpm mode task
  when: _host.cpc_dpm_enabled is defined and _host.cpc_dpm_enabled
  ansible.builtin.include_tasks: "dpm_mode.yaml"
