---

- name: Check role/task parameters
  ansible.builtin.fail:
    msg: "Error: loop control variable 'idx' is not defined"
  when: idx is not defined

- name: Include LPAR host variablese
  ansible.builtin.include_vars:
    file: "{{ inventory_dir }}/host_vars/{{ parm_lpar_names[idx] }}.yaml"
    name: _node

- name: Define local variables
  ansible.builtin.set_fact:
    _hmc_load_from_ftp_file_path: "{{ parm_lpar_prm_files[idx] }}"

- name: Lood classic mode task
  when: (_node.cpc_dpm_enabled is defined and not _node.cpc_dpm_enabled) or _node.cpc_dpm_enabled is not defined
  ansible.builtin.include_tasks: "classic_mode.yaml"

- name: Lood dpm mode task
  when: _node.cpc_dpm_enabled is defined and _node.cpc_dpm_enabled
  ansible.builtin.include_tasks: "dpm_mode.yaml"
