---

- name: Delete bootstrap, control, compute and infra nodes, if exists
  tags: delete_nodes
  ansible.builtin.shell: |
    virsh destroy {{ item }} || true
    virsh undefine {{ item }} --remove-all-storage --nvram || true
    META="{{ env.cluster.networking.metadata_name }}"
    virsh vol-delete --pool "${META}-vdisk" "{{ item }}.qcow2" || true
    virsh vol-delete --pool "${META}-vdisk" "{{ item }}-1.qcow2" || true
  loop: "{{ ([ env.cluster.nodes.bootstrap.vm_name | default()] + \
          (env.cluster.nodes.control.vm_name | default([]))+ \
          (env.cluster.nodes.compute.vm_name | default([])) + \
          (env.cluster.nodes.infra.vm_name | default([]))) | select() }}"
  register: delete_nodes
  changed_when: "('destroyed' in delete_nodes.stdout) or ('undefined' in delete_nodes.stdout)"

- name: Get and print virsh list
  tags: delete_nodes
  block:
    - name: Get virsh list
      ansible.builtin.command: virsh list
      register: cmd_virsh_list

    - name: Print virsh list
      ansible.builtin.debug:
        var: cmd_virsh_list.stdout_lines

- name: Get and print virsh image list
  tags: delete_nodes
  block:
    - name: Get virsh image list
      ansible.builtin.shell: |
        META="{{ env.cluster.networking.metadata_name }}"
        virsh vol-list "${META}-vdisk"
      register: cmd_virsh_imgage_list

    - name: Print virsh image list
      ansible.builtin.debug:
        var: cmd_virsh_image_list.stdout_lines
