---

- name: Find inventory directory from ansible.cfg
  tags: set_inventory
  ansible.builtin.shell: |
    set -o pipefail
    cat {{ ansible_config_file }} | grep 'inventory=' | cut -f2 -d"="
  args:
    executable: /bin/bash
  register: find_inventory
  changed_when: false

- name: Find absolute path to project.
  tags: set_inventory
  ansible.builtin.shell: |
    ansible_config="{{ ansible_config_file }}"
    echo "${ansible_config%/*}/"
  register: find_project
  changed_when: false

- name: Fail if network_mode is NAT and jumphost vars are undefined.
  tags: set_inventory
  ansible.builtin.fail:
    msg: "Error jumphost vars undefined: when env.network_mode is NAT, you must set all env.jumphost variables."
  when: ( env.network_mode | upper == 'NAT' ) and (env.jumphost.name is none or env.jumphost.ip is none or env.jumphost.user is none or env.jumphost.pass is none or env.jumphost.path_to_keypair is none)

- name: Create inventory with localhost, file server, KVM host, jumphost(optional) and bastion
  tags: set_inventory
  ansible.builtin.template:
    src: hosts.j2
    dest: "{{ find_project.stdout }}{{ find_inventory.stdout }}/hosts"
    mode: "0644"
    force: yes

- name: Refresh inventory
  tags: set_inventory
  ansible.builtin.meta: refresh_inventory

- name: Add path to Ansible private key in ansible.cfg
  tags: set_inventory
  ansible.builtin.lineinfile:
    line: "private_key_file=~/.ssh/{{ env.ansible_key_name }}"
    path: "{{ ansible_config_file }}"
    regexp: "private_key_file"
    state: present

- name: check inventory setup
  tags: set_inventory
  ansible.builtin.command: ansible-inventory --list
  register: inv_check
  changed_when: false
  failed_when: inv_check.rc != 0

- name: Re-read facts after changes made to inventory
  tags: set_inventory
  ansible.builtin.gather_facts:

- name: Refresh inventory
  tags: set_inventory
  ansible.builtin.meta: refresh_inventory
