---
- name: Wait for cluster operators
  tags: wait_for_cluster_operators
  ansible.builtin.include_tasks: check_co.yaml
  with_items:
    - "First"
    - "Second"
    - "Third"
    - "Fourth"
    - "Fifth and last"
  loop_control:
    loop_var: loop_count

- name: Verify that all cluster operators are available
  tags: wait_for_cluster_operators
  ansible.builtin.shell: |
    set -o pipefail
    # Check for 'AVAILABLE' state
    oc get co --no-headers 2> /dev/null | awk '{print $3}'
  register: co_check
  # Check for "True" and "False", in case output was empty for any reason
  until: ("True" in co_check.stdout) and ("False" not in co_check.stdout)
  retries: 15
  delay: 30
  failed_when: false

- name: Check cluster version operators
  tags: wait_for_cluster_operators
  ansible.builtin.import_role:
    name: wait_for_cluster_version

- name: Get and print final cluster operator status
  tags: wait_for_cluster_operators
  block:
    - name: Get final cluster operators
      ansible.builtin.shell: |
        oc get co
        echo
        oc get clusterversion
      register: oc_get_co
      changed_when: false

    - name: Print final cluster operators
      ansible.builtin.debug:
        var: oc_get_co.stdout_lines
