apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: enable-multipathd
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.2.0
    systemd:
      units:
        - name: multipathd.service
          enabled: true
