---

- name: Setup inventory
  hosts: localhost
  tags: localhost
  connection: local
  become: false
  gather_facts: true
  roles:
    - set_inventory

  post_tasks:
    - name: Test Ansible Galaxy collections connection
      ansible.builtin.shell: |
        ansible-galaxy --version
        curl -I https://galaxy.ansible.com/api/
      register: cmd_output

    - name: Print above cmd output
      ansible.builtin.debug:
        var: cmd_output.stdout_lines

    - name: Install Galaxy collections from local git repository
      tags: galaxy
      ansible.builtin.shell: |
        cd "{{ ansible_env.PWD }}/../collections"
        pwd
        ls -al
        ansible-galaxy collection install ./ansible-posix-2.1.0.tar.gz
        ansible-galaxy collection install ./community-general-12.2.0.tar.gz
        ansible-galaxy collection install ./community-libvirt-2.0.0.tar.gz
        ansible-galaxy collection install ./community-crypto-3.1.0.tar.gz
        ansible-galaxy collection install ./community-kubernetes-2.0.1.tar.gz
        ansible-galaxy collection install ./ibm-ibm_zhmc-1.10.0.tar.gz
      register: cmd_output

    - name: Print above cmd output
      ansible.builtin.debug:
        var: cmd_output.stdout_lines

    - name: Ensure Ansible Galaxy collections have been installed with latest version
      tags: galaxy
      ansible.builtin.command: ansible-galaxy collection install {{ item }} --upgrade
      loop: "{{ env.pkgs.galaxy }}"
      # Ignore errors
      failed_when: false

    - name: Find ibm_zhmc collection install location, required for LPAR mode
      tags: galaxy
      ansible.builtin.shell: |
        set -o pipefail
        ansible-galaxy collection list ibm.ibm_zhmc | awk '/ansible/{print $2}'
      args:
        executable: /bin/bash
      register: zhmc_path
      changed_when: false

    - name: Ensure zhmcclient requirements are installed.
      tags: galaxy
      ansible.builtin.pip:
        requirements: "{{ zhmc_path.stdout }}/ibm/ibm_zhmc/requirements.txt"
        executable: pip3
        extra_args: --upgrade
      when: zhmc_path.rc != 0

- name: Setup ssh keys
  hosts: localhost
  connection: local
  become: false
  gather_facts: true
  vars:
    ssh_target: ["{{ env.file_server.ip }}", "{{ env.file_server.user }}", "{{ env.file_server.pass }}", "{{ path_to_key_pair }}"]
  roles:
    - ssh_key_gen
    - ssh_agent
  post_tasks:
    - name: Test nslookup
      ansible.builtin.shell: |
        nslookup a3ep60
        nslookup a314lp60
      register: cmd_output

    - name: Print above cmd output
      ansible.builtin.debug:
        var: cmd_output.stdout_lines

