---

- name: Setup inventory
  hosts: localhost
  tags: localhost
  connection: local
  become: false
  gather_facts: true
  roles:
    - set_inventory

  post_tasks:
    - name: Ensure Ansible Galaxy collections have been installed (latest version)
      tags: galaxy
      ansible.builtin.command: ansible-galaxy collection install {{ item }} --upgrade
      loop: "{{ env.pkgs.galaxy }}"

    - name: Find ibm_zhmc collection install location, required for LPAR mode
      tags: galaxy
      ansible.builtin.shell: |
        set -o pipefail
        ansible-galaxy collection list ibm.ibm_zhmc | awk '/ansible/{print $2}'
      args:
        executable: /bin/bash
      register: zhmc_path
      changed_when: false

    - name: Ensure zhmcclient requirements are installed.
      tags: galaxy
      ansible.builtin.pip:
        requirements: "{{ zhmc_path.stdout }}/ibm/ibm_zhmc/requirements.txt"
        executable: pip3
        extra_args: --upgrade
      when: zhmc_path.rc != 0

    - name: Check KVM host 1 inventory host_vars with matching hostname
      tags: lpar_check
      ansible.builtin.stat:
        path: "{{ inventory_dir }}/host_vars/{{ env.z.lpar1.hostname }}.yaml"
      when: env.z.lpar1.hostname is defined
      register: lpar_host_vars
      failed_when: not lpar_host_vars.stat.exists
      ignore_errors: true

    - name: Check KVM host 2 inventory host_vars with matching hostname
      tags: lpar_check
      ansible.builtin.stat:
        path: "{{ inventory_dir }}/host_vars/{{ env.z.lpar2.hostname }}.yaml"
      when: env.z.lpar2.hostname is defined
      register: lpar_host_vars
      failed_when: not lpar_host_vars.stat.exists

    - name: Check KVM host 3 inventory host_vars with matching hostname
      tags: lpar_check
      ansible.builtin.stat:
        path: "{{ inventory_dir }}/host_vars/{{ env.z.lpar3.hostname }}.yaml"
      when: env.z.lpar3.hostname is defined
      register: lpar_host_vars
      failed_when: not lpar_host_vars.stat.exists

- name: Setup ssh keys
  hosts: localhost
  connection: local
  become: false
  gather_facts: true
  vars:
    ssh_target: ["{{ env.file_server.ip }}", "{{ env.file_server.user }}", "{{ env.file_server.pass }}", "{{ path_to_key_pair }}"]
  roles:
    - ssh_key_gen
    - ssh_agent
#    - ssh_copy_id #to file server
