---

- name: Setup localhost environment
  hosts: localhost
  tags: localhost
  connection: local
  become: false
  gather_facts: true
  pre_tasks:
    - name: Setup Ansible Galaxy Collections
      ansible.builtin.include_role:
        name: galaxy_setup
      run_once: true

    - name: Define 'env_ssh_key_path' variable
      when: env_ssh_key_path is not defined
      ansible.builtin.lineinfile:
        path: "{{ playbook_dir }}/../inventories/default/group_vars/all.yaml"
        regexp: '^env_ssh_key_path:'
        line: "env_ssh_key_path: {{ lookup('config', 'DEFAULT_PRIVATE_KEY_FILE') | default('~/.ssh/ansible-ocp-vip', true) }}"
        state: present

    - name: Check if AOP_RELEASE environment variable is defined
      ansible.builtin.set_fact:
        aop_release_value: "{{ lookup('env', 'AOP_RELEASE') }}"

    - name: Update 'env_ocp_release' and reload OCP release variables, if AOP_RELEASE is set
      when: aop_release_value | length > 0
      block:
        - name: "Update 'env_ocp_release' in all.yaml file to {{  aop_release_value }}"
          ansible.builtin.lineinfile:
            path: "{{ playbook_dir }}/../inventories/default/group_vars/all.yaml"
            regexp: '^env_ocp_release:\s+'
            line: 'env_ocp_release: "{{ aop_release_value }}"'
            backrefs: false

        - name: Display current env_ocp_release value
          ansible.builtin.debug:
            msg: "env_ocp_release is set to: '{{ aop_release_value }}'"

    - name: Reload group_vars to pick up the updated env_ocp_release
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/../inventories/default/group_vars/all.yaml"

  roles:
    - ssh_key_gen_v2      # Create required SSH key on controller
    - set_inventory

  # Info:
  # - role: ssh_copy_id_v2
  #   vars:
  #     parm_host: "{{ env.systems.host1 | default('') }}"
  post_tasks:
    - name: Execute ssh_copy_id_v2 for all defined systems and file_server
      ansible.builtin.include_role:
        name: ssh_copy_id_v2
      loop:
        - "{{ env.systems.host1 | default('') }}"
        - "{{ env.systems.host2 | default('') }}"
        - "{{ env.systems.host3 | default('') }}"
        - "{{ env.file_server | default('') }}"
      vars:
        parm_host: "{{ item }}"
      when: item.ip is defined
      loop_control:
        # This prevents Ansible from dumping the variable data into the logs.
        label: "Delegate to host IP {{ item.ip | default('') }}"
