---

- name: Prepare KVM host(s)
  hosts: kvm_host
  tags: setup, section_2
  gather_facts: true
  become: true
  vars:
    packages: "{{ env.pkgs.kvm }}"
  roles:
    - { role: attach_subscription, when: env.redhat.manage_subscription }
    - install_packages
    - httpd
  post_tasks:
    - name: Add ports to firewall
      tags: firewall-libvirt, libvirt
      ansible.posix.firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled

    - name: Start and enable libvirt
      tags: firewall-libvirt, libvirt
      ansible.builtin.service:
        name: libvirtd
        enabled: yes
        state: started

    - name: Permit traffic in libvirt zone
      tags: firewall-libvirt, libvirt
      ansible.posix.firewalld:
        service: http
        permanent: yes
        state: enabled
        zone: libvirt
        immediate: true

    - name: Set libvirt management to libvirt group instead of root.
      tags: libvirt
      ansible.builtin.lineinfile:
        path: /etc/libvirt/qemu.conf
        regexp: '#group = "root"'
        line: 'group = "libvirt"'
        backup: true

    - name: Get user home directory
      tags: libvirt
      ansible.builtin.shell: |
        set -o pipefail
        getent passwd {{ ansible_user }} | awk -F: '{ print $6 }'
      changed_when: false
      register: user_home

    - name: Show user_home variable
      ansible.builtin.debug:
        var: user_home

    - name: Check if directory {{ user_home.stdout }}/.config/libvirt exists
      tags: libvirt
      ansible.builtin.stat:
        path: "{{ user_home.stdout }}/.config/libvirt"
      register: home_config_libvirt

    - name: Create directory {{ user_home.stdout }}/.config/libvirt
      tags: libvirt
      ansible.builtin.file:
        path: "{{ user_home.stdout }}/.config/libvirt"
        state: directory
        mode: "0755"
      when: not home_config_libvirt.stat.exists

    # TODO: fix hack
    - name: Hack for bug 'https://github.com/IBM/Ansible-OpenShift-Provisioning/issues/188'
      tags: libvirt
      ansible.builtin.file:
        path: "/home/root/.config/libvirt"
        state: directory
        mode: "0755"

    - name: Create file for user's custom libvirt configurations.
      tags: libvirt
      ansible.builtin.file:
        path: "{{ user_home.stdout }}/.config/libvirt/libvirt.conf"
        state: touch
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0644"

    - name: Set default uri connection to qemu:///system.
      tags: libvirt
      ansible.builtin.lineinfile:
        path: "{{ item }}"
        regexp: '#uri_default = "qemu:///system"'
        line: 'uri_default = "qemu:///system"'
        backup: true
      loop:
        - /etc/libvirt/qemu.conf
        - "{{ user_home.stdout }}/.config/libvirt/libvirt.conf"
        - /etc/libvirt/libvirt.conf

    - name: Ensure KVM admin user is part of groups 'kvm', 'libvirt'.
      tags: groups, group, libvirt
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        append: true
        groups: kvm,libvirt

    - name: Restart libvirt
      tags: firewall-libvirt, libvirt
      ansible.builtin.service:
        name: libvirtd
        enabled: yes
        state: restarted

    - name: Ensure Cockpit console is enabled and started
      tags: cockpit
      ansible.builtin.systemd:
        name: cockpit.socket
        enabled: true
        state: started

- name: Configure storage
  hosts: kvm_host
  tags: setup, section_3
  become: true
  roles:
    - { role: macvtap, when: env.network_mode | upper != 'NAT' }
    - configure_storage
