# Assume we have an existing ftp/http server already
- name: 4 create bastion
  # Install bastion always on 2nd LPAR definition
  hosts: kvm_host[1]
  become: false
  vars_files:
    - "{{ inventory_dir }}/group_vars/all.yaml"
    - "{{ inventory_dir }}/host_vars/{{ env.z.lpar1.hostname }}.yaml"
  roles:
    - common
    - { role: create_bastion, when: env.bastion.create == True }
