# Assume we have an existing ftp/http server already
- name: 4 create bastion
  # Bastion will be installed on kvm host which is defined in env.bastion.kvm_hostname
  hosts: kvm_host
  become: false
  vars_files:
    - "{{ inventory_dir }}/group_vars/all.yaml"
    - "{{ inventory_dir }}/host_vars/{{ env.bastion.kvm_hostname }}.yaml"
  roles:
    - common
    - { role: create_bastion, when: env.bastion.create == True and inventory_hostname == env.bastion.kvm_hostname }
