---

- name: 5 setup bastion - copy SSH key from localhost to access bastion.
  hosts: localhost
  tags: ssh, ssh_copy_id, section_1
  gather_facts: true
  vars:
    ssh_target: ["{{ env.bastion.networking.ip }}", "{{ env.bastion.access.user }}", "{{ env.bastion.access.pass }}", "{{ path_to_key_pair }}"]
  roles:
    - ssh_copy_id

- name: 5 setup bastion - configure bastion node with essential services
  hosts: bastion
  tags: services, section_2
  become: true
  vars:
    packages: "{{ env.pkgs.bastion }}"
    control_node_count: "{{ env.cluster.nodes.control.ip | length }}"
  pre_tasks:
    - name: Import initial-resolv.yaml
      ansible.builtin.import_role:
        name: dns
        tasks_from: initial-resolv.yaml
    - name: Delete motd message
      ansible.builtin.shell: |
        rm -f /etc/motd.d/insights-client
  roles:
    - { role: attach_subscription, when: env.redhat.manage_subscription }
    - install_packages
    - ssh_ocp_key_gen
    - set_firewall
    - { role: dns, when: env.bastion.options.dns }
    # - dns_check
    - { role: haproxy, when: env.bastion.options.loadbalancer.on_bastion }
    - httpd

- name: 5 setup bastion - get OCP images
  hosts: bastion
  tags: get_ocp, section_3
  become: true
  roles:
    - common
    - get_ocp
