---
- name: 7 OCP verification
  hosts: bastion
  environment:
    KUBECONFIG: "{{ '/home/' if (env.bastion.access.user != 'root') else '/'}}{{ env.bastion.access.user }}/.kube/config"
  gather_facts: true
  roles:
    - check_nodes
    - role: approve_certs
      vars:
        approve_certs_cleanup: true
    - wait_for_cluster_operators
    - wait_for_install_complete
