---

# Tune OCP cluster
- name: 8 Tune OCP CLuster nodes
  hosts: kvm_host
  gather_facts: false
  vars_files:
    - "{{ inventory_dir }}/group_vars/all.yaml"
  roles:
    - role: tune_kvm_domain
      param_kvm_domain_list: "{{ (env.cluster.nodes.control.vm_name | default([])) + \
        (env.cluster.nodes.compute.vm_name | default([])) }}"
