# Use this if you want to re-install nodes with a new OCP version
---
- import_playbook: 0_setup.yaml

- name: Re-Install cluster - Copy SSH key from localhost to access bastion
  hosts: localhost
  tags: ssh, ssh_copy_id, section_1
  gather_facts: true
  roles:
    - role: ssh_copy_id_v2
      vars:
        parm_host:
          ip: "{{ env.bastion.networking.ip }}"
          user: "{{ env.bastion.access.user }}"
          pass: "{{ env.bastion.access.pass }}"
        parm_ssh_key_path: "{{ env_ssh_key_path }}"

- name: Re-Install cluster - Update ignitions and other install files
  hosts: bastion
  pre_tasks:
    # - name: Import initial-resolv.yaml
    #   ansible.builtin.import_role:
    #     name: dns
    #     tasks_from: initial-resolv.yaml

    # - name: Check if OCP architecture matches Bastion host architecture
    #   ansible.builtin.shell: |
    #     set -o pipefail
    #     ARCH=$(uname -m | sed 's/aarch64/arm64/;s/x86_64/amd64/')
    #     if [[ "${ARCH}" -ne "{{ env.install_config.control.architecture }}" ]]; then
    #        echo "ERROR: Install Bastion host with '{{ env.install_config.control.architecture }}' architecture !"
    #        exit 1
    #     fi
    #   changed_when: false

  roles:
    - common
    - { role: dns, when: env.bastion.options.dns }
    - { role: haproxy, when: env.bastion.options.loadbalancer.on_bastion }
    - get_ocp

- import_playbook: 5b_setup_bastion_test_env.yaml
- import_playbook: 6_create_nodes.yaml
- import_playbook: 7_ocp_verification.yaml
#- import_playbook: 8_tune_cluster.yaml
#  when: tune_cluster is defined and tune_cluster
