---
- name: Include LPAR host variables
  ansible.builtin.include_vars:
    file: "{{ inventory_dir }}/host_vars/{{ lpar_name }}.yaml"
    name: _node

- name: Stop dpm mode partition (async)
  when: _node.cpc_dpm_enabled is defined and _node.cpc_dpm_enabled
  vars:
    _zhmc_auth:
      userid: "{{ _node.hmc.auth.user }}"
      password: "{{ _node.hmc.auth.pass }}"
      verify: false
  block:
    - name: "Stop dpm mode partition (async) {{ _node.lpar.name }}"
      ibm.ibm_zhmc.zhmc_partition:
        hmc_host: "{{ _node.hmc.host }}"
        hmc_auth: "{{ _zhmc_auth }}"
        cpc_name: "{{ _node.cpc_name }}"
        name: "{{ _node.lpar.name }}"
        state: stopped
      # Run in background for up to 10 mins, return immediately
      async: 600
      poll: 0
      register: task_result
      until: >
        "object is busy with another operation" not in (task_result.msg | default(""))
        and
        "trying to obtain a list of the software" not in (task_result.msg | default(""))
      retries: 30
      delay: 30
      # Retry on busy msg:
      # "msg": "HTTPError: 409,2: The operation could not be completed because the object is busy with another operation.
      # Wait for that operation to complete, and then try this operation again.
      # Other error:
      # "msg": "HTTPError: 409,131: An error has occurred while trying to obtain a list of the software that can be loaded.
